version: "3"
services:

  nifi_monitor:
    build:
      context: .
    container_name: nifi_monitor
    image: nifi_monitor
    ports:
      - "9092:5000"
    environment:
     - BASE_URL=https://hrz-nifi01-prd.payoneer.com:9443
     - USERNAME=nifi_cluster
     - PASSWORD=vLdNToId|B#W:4F*W=W+
